AllCops:
  TargetRubyVersion: 2.2
  Include:
    - '**/Gemfile'
    - lib/**/*.rb
    - spec/**/*.rb
    - gemirro.gemspec
  Exclude:
    - files/**/*
    - templates/**/*
    - spec/**/*

Naming/FileName:
  Exclude:
    - Rakefile
ModuleLength:
  Enabled: false
MethodLength:
  Enabled: false
ClassLength:
  Enabled: false
ParameterLists:
  Enabled: false
Metrics/CyclomaticComplexity:
  Enabled: false
Metrics/PerceivedComplexity:
  Enabled: false
Metrics/AbcSize:
  Enabled: false
Metrics/BlockLength:
  Enabled: false
Security/MarshalLoad:
  Enabled: false
Style/ExpandPathArguments:
  Enabled: false
