AllCops:
  SuggestExtensions: false
  NewCops: enable
  TargetRubyVersion: 2.5
  Include:
    - '**/Gemfile'
    - lib/**/*.rb
    - spec/**/*.rb
    - gemirro.gemspec
  Exclude:
    - files/**/*
    - templates/**/*
    - spec/**/*
    - vendor/**/*

Naming/FileName:
  Exclude:
    - Rakefile
Metrics/MethodLength:
  Enabled: false
Metrics/ClassLength:
  Enabled: false
Metrics/CyclomaticComplexity:
  Enabled: false
Metrics/PerceivedComplexity:
  Enabled: false
Metrics/AbcSize:
  Enabled: false
Metrics/BlockLength:
  Enabled: false
Security/MarshalLoad:
  Enabled: false
Style/ExpandPathArguments:
  Enabled: false
Style/OptionalBooleanParameter:
  Enabled: false
Lint/MissingSuper:
  Enabled: false
Style/TrailingUnderscoreVariable:
  Enabled: false
