# frozen_string_literal: true

require 'builder'
require 'confstruct'
require 'digest/sha2'
require 'fileutils'
require 'json'
require 'logger'
require 'net/http'
require 'openssl'
require 'optparse'
require 'parallel'
require 'rubygems'
require 'rubygems/indexer'
require 'rubygems/user_interaction'
require 'stringio'
require 'tempfile'
require 'zlib'

$LOAD_PATH.unshift(File.expand_path('../', __FILE__)) unless $LOAD_PATH.include?(File.expand_path('../', __FILE__))

require 'gemirro/version'
require 'gemirro/configuration'
require 'gemirro/utils'
require 'gemirro/gem'
require 'gemirro/gem_version'
require 'gemirro/gem_version_collection'
require 'gemirro/http'
require 'gemirro/indexer'
require 'gemirro/source'
require 'gemirro/mirror_directory'
require 'gemirro/mirror_file'
require 'gemirro/versions_file'
require 'gemirro/versions_fetcher'
require 'gemirro/gems_fetcher'

require 'gemirro/cli'
